server.port: 9000
app.tasks.endpointMessage: How you doin!
spring:
  h2:
    console:
      enabled: true
logging:
  level:
    org.springframework.jdbc.core: DEBUG

spring.jpa.hibernate.ddl-auto: none